/********************************************************************************
   Script: ProjectSQL.sql
   Description: Creates and populates the Project 0 database.
   DB Server: Project0-SQL
   Author: Jonathan Gutierrez
********************************************************************************/

/*******************************************************************************
   Create Tables
********************************************************************************/

CREATE TABLE [Customers]
(
    [CustomerID] INT NOT NULL IDENTITY UNIQUE,
    [FirstName] NVARCHAR(160) NOT NULL,
    [LastName] INT NOT NULL,
	[CardNumber] INT NOT NULL,
    CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED ([CustomerID])
);
GO

CREATE TABLE [Order]
(
	[CustomerID] INT NOT NULL IDENTITY UNIQUE,
    [OrderID] INT NOT NULL IDENTITY UNIQUE,
    [ProductID] INT NOT NULL,
);

GO
CREATE TABLE [Product]
(
	[ProductID] INT NOT NULL IDENTITY UNIQUE,
    [Price] DECIMAL NOT NULL,
    [ProductName] NVARCHAR(160) NOT NULL,
    CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED ([ProductID])
);
GO

/*******************************************************************************
   Create Foreign Keys
********************************************************************************/


ALTER TABLE [Order] ADD CONSTRAINT [FK_OrderCustID]
    FOREIGN KEY ([CustomerID]) REFERENCES [Customers] (CustomerID) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

CREATE INDEX [FK_OrderCustID] ON [Order] ([OrderID]);
GO

ALTER TABLE [Order] ADD CONSTRAINT [FK_OrderProdID]
    FOREIGN KEY ([ProductID]) REFERENCES [Product] (ProductID) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

CREATE INDEX [FK_OrderProdID] ON [Order] ([ProductID]);
GO

/*******************************************************************************
   Adding 3 Records into each table
********************************************************************************/
INSERT INTO [Customers] ([CustomerID], [FirstName], [LastName]) VALUES (1, N'Jonathan',N'Gutierrez');
INSERT INTO [Customers] ([CustomerID], [FirstName], [LastName]) VALUES (2, N'Alan',N'Walker');
INSERT INTO [Customers] ([CustomerID], [FirstName], [LastName]) VALUES (3, N'Chris',N'Allen');
INSERT INTO [Order] ([CustomerID], [OrderID], [ProductID]) VALUES (1, 1,1);
INSERT INTO [Order] ([CustomerID], [OrderID], [ProductID]) VALUES (1, 2,2);
INSERT INTO [Order] ([CustomerID], [OrderID], [ProductID]) VALUES (1, 3,3);
INSERT INTO [Order] ([CustomerID], [OrderID], [ProductID]) VALUES (2, 4,1);
INSERT INTO [Order] ([CustomerID], [OrderID], [ProductID]) VALUES (2, 5,2);
INSERT INTO [Order] ([CustomerID], [OrderID], [ProductID]) VALUES (2, 6,3);
INSERT INTO [Order] ([CustomerID], [OrderID], [ProductID]) VALUES (3, 7,1);
INSERT INTO [Order] ([CustomerID], [OrderID], [ProductID]) VALUES (3, 8,2);
INSERT INTO [Order] ([CustomerID], [OrderID], [ProductID]) VALUES (3, 9,3);
/*******************************************************************************
   Adding Product iPhone Priced at $200
********************************************************************************/
INSERT INTO [Product] ([ProductID], [ProductName], [Price]) VALUES (4, 'iPhone', 200);
/*******************************************************************************
   Adding Customer Tina Smith
********************************************************************************/
INSERT INTO [Customers] ([CustomerID], [FirstName], [LastName]) VALUES (4, N'Tina',N'Smith');
/*******************************************************************************
   Create order for Tina Smith bought an iPhone
********************************************************************************/
INSERT INTO [Order] ([CustomerID], [OrderID], [ProductID]) VALUES (4, 10, 4);
/*******************************************************************************
   report all orders for Tina Smith
********************************************************************************/
SELECT [OrderID] FROM [Order] WHERE [CustomerID] = 4;
/*******************************************************************************
   report all revenue generated by sales of iPhone
********************************************************************************/
SELECT SUM([Price]) FROM [Product] WHERE [ProductID] = 4;
/*******************************************************************************
   Increase the price of iPhone to 250
********************************************************************************/
UPDATE [Product] SET Price = 250 WHERE [ProductName] = 'iPhone';